### ISSUE TITLE
Need a history of readings to create the graph

### ISSUE THREAD

**Issue by janie-t** [WhareHauora/App#68]
Is this data already stored somewhere in the database?

**Comment by Br3nda** [comment]
The API method is https://app.wharehauora.nz/api/v1/rooms/{{room_id}}/readings
But i see it return an error for me right now. I can look at it tommorrow.

**Comment by MeghanHughes** [comment]
Relates to https://github.com/WhareHauora/App/issues/41

**Comment by Br3nda** [comment]
That api method should work now

**Comment by MeghanHughes** [comment]
Hey @anna-marie-vos I still get error when I try this method - can you try? In case it's just me lol

**Comment by MeghanHughes** [comment]
Hey @Br3nda I still get a 500 when I make a call to https://app.wharehauora.nz/api/v1/rooms/5/readings

**Comment by Br3nda** [comment]
Api pull request is waiting for review.
https://github.com/WhareHauora/wharehauora-server/pull/385

**Comment by Br3nda** [comment]
the linked pull request also has CRUD methods

This might be useful too:
this looks useful for next project https://github.com/redux-json-api/redux-json-api
(but only if you use redux, so immv)

**Comment by Br3nda** [comment]
i'm gonna wait for midday to see if i can get a review from anyone.. and if not i'll push the merge and get the new api methods on the server for you

**Comment by janie-t** [comment]
The graph is not implemented at this stage - should remove from app for now?

**Comment by MeghanHughes** [comment]
It's set up on this branch, and @Br3nda has created an api route for a week's readings. https://github.com/WhareHauora/App/tree/mh/sensorGraph

It needs some work, as documented in #41
